Repository pringa-uvlhub/uvlhub, pull requests merged in 2024-12, with the labels that each got.

#20 Feature/remember my password
  .env.local.example
  app/__init__.py
  app/extensions.py
  app/modules/auth/forms.py
  app/modules/auth/models.py
  app/modules/auth/routes.py
  app/modules/auth/services.py
  app/modules/auth/templates/auth/forgot_password.html
  app/modules/auth/templates/auth/login_form.html
  app/modules/auth/templates/auth/reset_password.html
  requirements.txt
Labels: feature, low WI

#18 Feature/ Sign up validation feature and some tests added
  .env.local.example
  .github/workflows/codacy.yml
  .github/workflows/render.yml
  .github/workflows/tests.yml
  app/__init__.py
  app/modules/auth/routes.py
  app/modules/auth/services.py
  app/modules/auth/templates/auth/confirmation.html
  app/modules/auth/templates/auth/email_verification.html
  app/modules/auth/templates/auth/login_form.html
  app/modules/auth/templates/auth/signup_form.html
  app/modules/auth/tests/locustfile.py
  app/modules/auth/tests/test_selenium.py
  app/modules/auth/tests/test_unit.py
  requirements.txt
Labels: feature

#120 Fix: incomplete requirements and fix dashboard bug
  app/modules/admin/routes.py
  app/modules/admin/templates/admin/no_data.html
  requirements.txt
Labels: bug, priority: critical
